### ISSUE TITLE
Clicking a disabled button still fires click event

### ISSUE THREAD

**Issue by znewton** [AlaskaAirlines/OrionStatelessComponents__ods-button#11]
# Issue report

## Expected Behavior

Clicking an `ods-button` with  `disabled="true"` attribute set does not fire click handler

## Current Behavior

Clicking an `ods-button` with  `disabled="true"` attribute set fires click handler

## Possible Solution

Disable click event propagation when attribute `disabled` is true

## Steps to Reproduce (for bugs)

1. Setup a React project with ods-button integrated
2. Add an ods-button with `onClick={alert('Hey, I\'m disabled')}` and `disabled="true"`
3. Boot up the project and click the ods-button
4. Witness the alert appear

## Context

Developing a project that has a disabled ods-button if a form isn't fully filled out, but when clicking the disabled button, the event handler still fires, leading to a page redirect. We will fix this problem by manually disabling the redirect using the same state that we are using to disable the button.

## Your Environment

* Version used:
* Browser Name and version:  Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 (desktop)
* Link to your project: (private)

**Comment by blackfalcon** [comment]
I am wondering if it's the responsibility of the component to manage this? 

The ods-button is not creating the click event, nor is it managing it. Its role is to only manage the appearance of the state passed into the component. 

The HTML button itself does not manage click events nor do I believe that this web component should.

**Comment by znewton** [comment]
Tested it out and the raw HTML `<button>` does in fact block the onClick handler when disabled=true. Spin up a quick create-react-app to see what I mean.

```jsx
<button disabled onClick={() => alert('hello')}>Hello</button>
```

**Comment by blackfalcon** [comment]
The issue is that the click event is being placed on <ods-button> itself, not the <button> element contained within the shadowDOM. 

The resolution to this issue is to move the click event FROM the outer element to the inner <button> element, then the element would respond as expected.
