### ISSUE TITLE
Context does not apply in IE11

### ISSUE THREAD

**Issue by geoffrey1218** [AlaskaAirlines/OrionStatelessComponents__ods-button#15]
# Issue report

## Expected Behavior

Buttons respond to the context property in IE11.

## Current Behavior

Buttons do not respond to the context property in IE11.

## Possible Solution

IE11 does not support [CSS unset](https://caniuse.com/#feat=css-unset-value), so `width: unset` may be causing issues.

## Steps to Reproduce (for bugs)

1. Run the element locally using the Polymer CLI
2. Navigate to http://127.0.0.1:8000/demo/ in IE11 
3. Note that all button types behave as if context was set to true

## Your Environment

* Version used: 1.0.521026034
* Browser Name and version: IE11
* Operating System and version (desktop or mobile): Windows 7
* Link to your project: n/a

**Comment by ecommerceUXdesign** [comment]
Closed with https://github.com/AlaskaAirlines/OrionStatelessComponents__ods-button/commit/205cacfeba670a09c2727a93efe00f7f7099ed33

**Comment by blackfalcon** [comment]
oops!

**Comment by geoffrey1218** [comment]
There's still one more!

https://github.com/AlaskaAirlines/OrionStatelessComponents__ods-button/blob/71cfaabf356cf2819812cd8c5f1878b50717daf3/src/shape.json#L56-L59

Used here: 

https://github.com/AlaskaAirlines/OrionStatelessComponents__ods-button/blob/71cfaabf356cf2819812cd8c5f1878b50717daf3/src/style.scss#L159-L161
