### ISSUE TITLE
Hover states and right alignment do not apply using altImports

### ISSUE THREAD

**Issue by geoffrey1218** [AlaskaAirlines/OrionStatelessComponents__ods-button#16]
# Issue report

## Expected Behavior

Hover states and right alignment apply while using the altImport CSS.

## Current Behavior

Hover states and right alignment do not apply while using the altImport CSS.

## Possible Solution

The CSS is not being applied due to the :host pseudo-class. Either do not use :host in the CSS or replace it when generating the altImports.

## Steps to Reproduce (for bugs)

1. Use the following HTML. The button HTML was copied from the demo's rendering of ods-button.
```
<html>

<head>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <div>
        <button aria-labelledby="odsButtonString" aria-label="Default state" title="Default state" class="button   ">
            <span id="odsButtonString">
                Default state
            </span>

            <span class="dancingDots ">
                <div class="dots">
                    <div class="block">
                        <div></div>
                    </div>
                    <div class="block">
                        <div></div>
                        <div></div>
                    </div>
                    <div class="block">
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
            </span>
        </button>
    </div>
</body>

</html>
```
2. Copy `altImportsCanonical/style.css` into the same folder as the HTML file.
3. Open the HTML file in your browser.
4. Notice that the button does not react to hovers.

## Your Environment

* Version used: 1.0.521026034
* Browser Name and version: Chrome 73.0.3683.103
* Operating System and version (desktop or mobile): Windows 7
* Link to your project: n/a

**Comment by ecommerceUXdesign** [comment]
closed with https://github.com/AlaskaAirlines/OrionStatelessComponents__ods-button/commit/205cacfeba670a09c2727a93efe00f7f7099ed33
