### ISSUE TITLE
Rethink the pre-processed CSS per component 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/OrionStatelessComponents__ods-button#17]
Re: #15 and #16 

This is an overall redevelopment of the pre-processed CSS solution that is in place for teams that cannot or unable to use the full Orion Design System process as designed. 

Issues to resolve include issues related to #15 and #16, but also need to rethink how the files are processed as well including additional resources needed for use with the variable versions. 

Currently, variable versions are being produced, but are unusable unless the team is building Design Tokens as well. This fix would mean producing a CSS custom property file for component CSS, but NOT include variable referneces to Design Tokens themselves. These should be referenced from building tokens or using pre-processed tokens from the tokens npm.

**Comment by ecommerceUXdesign** [comment]
closed with https://github.com/AlaskaAirlines/OrionStatelessComponents__ods-button/commit/205cacfeba670a09c2727a93efe00f7f7099ed33
