### ISSUE TITLE
altImports contain invalid CSS

### ISSUE THREAD

**Issue by geoffrey1218** [AlaskaAirlines/OrionStatelessComponents__ods-button#25]
# Issue report

`altImportsCanonical\style_clean.scss` contains the invalid CSS selector `&(.focus-visible)`, making it impossible to build any .scss file including it.

```
&(.focus-visible) {
  * {
    &:focus {
      box-shadow: 0 0 0 3px $tomato_f26135;
      outline: 3px solid $tomato_f26135;
    }
  }
}
```

## Expected Behavior

`style_clean.scss` contains valid css

## Current Behavior

`style_clean.scss` does not contain valid css, resulting in the following error message.

```
1>  Error in plugin 'sass'
1>  Message:
1>      node_modules\@alaskaairux\ods-button\altImportsCanonical\style_clean.scss
1>EXEC : error : Invalid CSS after "&": expected selector, was "(.focus-visible) {"
1>          on line 23 of node_modules/@alaskaairux/ods-button/altImportsCanonical/style_clean.scss
1>          from line 73 of Styles/cancel.scss
1>  >> &(.focus-visible) {
1>  
1>     ^
```

## Steps to Reproduce (for bugs)

1. Include `style_clean.scss` in a scss file and attempt to build the css

## Your Environment

* Version used: 2.4.532527175

**Comment by blackfalcon** [comment]
Be aware of API update to the location of altImport assets. 

https://github.com/AlaskaAirlines/OrionStatelessComponents__ods-button#alternate-build-solutions
