### ISSUE TITLE
Sentence case button strings 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/OrionStatelessComponents__ods-button#30]
# Issue report

Update the button component so that the strings entered are always sentence case. 

## Expected Behavior

When seeing a button in a UI, the string inside should have sentence case.

## Current Behavior

If all letters are in lower case, the string in the button is presented as lower case.

## Possible Solution

Update CSS rules and maybe JavaScript to always ensure that the string is sentence case.

**Comment by blackfalcon** [comment]
This issue has been identified as a bug with Webkit. See the following link for details in Bugzilla. 

https://bugs.webkit.org/show_bug.cgi?id=202176

**Comment by ecommerceUXdesign** [comment]
Due to other issues with this CSS feature and web components, the support for auto capitalization has been removed.
