### ISSUE TITLE
Buttons to support left alignment 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/OrionStatelessComponents__ods-button#6]
# Issue report

Your issue may already be reported! Please search on the issue tracker before creating one.

## Expected Behavior
When ods-button is used, by default the button will stick to the right and be responsive. With the use of the context attribute, it will be 100%. There is no ability to get the button to stick to the left if the design requires this placement. 

## Current Behavior
Stick to the right or 100%

## Possible Solution
Create another prop attribute for the ods-button API that will support left placement.

**Comment by ecommerceUXdesign** [comment]
Support for this request has not maintained. Closing.
